name: konoeki_de_oritimer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.3
  intl: ^0.18.1

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
